CatalogsApp.Web/Controllers/ProductCatalogController.cs
using CatalogApp.Business.Products.Queries;
using CatalogsApp.Api.Models.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList;

namespace CatalogsApp.Web.Controllers
{
    public class ProductCatalogController : Controller
    {
        private static readonly int PageSize = 20;

        public async Task<ViewResult> Index(string sortBy, string currentFilter, string keyword, int? page)
        {
            IPagedList<ProductCatalogModel> pagedList = null;
            var totalItemCount = 0;

            if (keyword != null)
            {
                page = 1;
            }
            else
            {
                keyword = currentFilter;
            }

            ViewBag.CurrentSort = sortBy;
            ViewBag.CurrentFilter = keyword;

            var query = new GetProductCatalogsQuery
            {
                Keyword = keyword,
                Sort = sortBy,
                Skip = (page - 1) * PageSize,
                Limit = PageSize,
            };

            IList<ProductCatalogModel> productCatalogs = null;

            using (var client = GetApiClient())
            {
                var queryString = GetSearchQueryString(query);
                var apiResponse = await client.GetAsync("product_catalogs" + queryString);

                if (apiResponse.IsSuccessStatusCode)
                {
                    productCatalogs = await apiResponse.Content.ReadAsAsync<IList<ProductCatalogModel>>();

                    if (apiResponse.Headers.Contains("X-Total-Count"))
                    {
                        totalItemCount = int.Parse(apiResponse.Headers.GetValues("X-Total-Count").First());
                    }

                    ViewBag.ExportLink = GetExportLink(query);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact system administrator.");
                }
            }

            if (productCatalogs?.Count > 0)
            {
                pagedList = new StaticPagedList<ProductCatalogModel>(productCatalogs, page ?? 1, query.Limit.Value, totalItemCount);
            }

            return View(pagedList);
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProductCatalogModel productCatalog = null;

            using (var client = GetApiClient())
            {
                var apiResponse = await client.GetAsync($"product_catalogs/{id.Value}");

                if (apiResponse.IsSuccessStatusCode)
                {
                    productCatalog = await apiResponse.Content.ReadAsAsync<ProductCatalogModel>();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact system administrator.");
                }
            }

            if (productCatalog == null)
            {
                return HttpNotFound();
            }

            return View(productCatalog);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductCatalogModel model)
        {
            if (ModelState.IsValid)
            {
                using (var client = GetApiClient())
                {
                    var apiResponse = await client.PostAsXmlAsync($"product_catalogs", model);

                    if (!apiResponse.IsSuccessStatusCode)
                    {
                        ModelState.AddModelError(string.Empty, "Server error. Please contact system administrator.");
                    }
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var productCatalog = await GetProductCatalogAsync(id.Value);

            if (productCatalog == null)
            {
                return HttpNotFound();
            }

            return View(productCatalog);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var productCatalog = await GetProductCatalogAsync(id.Value);

            if (TryUpdateModel(productCatalog, "",
               new string[] { "Code", "Name", "Price", "LastUpdated" }))
            {
                using (var client = GetApiClient())
                {
                    var apiResponse = await client.PutAsXmlAsync($"product_catalogs/{id}", productCatalog);

                    if (apiResponse.IsSuccessStatusCode)
                    {
                        await apiResponse.Content.ReadAsAsync<ProductCatalogModel>();
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Server error. Please contact system administrator.");
                    }
                }

                return RedirectToAction("Index");
            }

            return View(productCatalog);
        }

        public async Task<ActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }

            var productCatalog = await GetProductCatalogAsync(id.Value);

            if (productCatalog == null)
            {
                return HttpNotFound();
            }

            return View(productCatalog);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            var productCatalog = await GetProductCatalogAsync(id);

            if (productCatalog == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            using (var client = GetApiClient())
            {
                var apiResponse = await client.DeleteAsync($"product_catalogs/{id}");

                if (!apiResponse.IsSuccessStatusCode)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Server error. Please contact system administrator.");
                }
            }

            return RedirectToAction("Index");
        }

        private async Task<ProductCatalogModel> GetProductCatalogAsync(int id)
        {
            ProductCatalogModel productCatalog = null;

            using (var client = GetApiClient())
            {
                var apiResponse = await client.GetAsync($"product_catalogs/{id}");

                if (apiResponse.IsSuccessStatusCode)
                {
                    productCatalog = await apiResponse.Content.ReadAsAsync<ProductCatalogModel>();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact system administrator.");
                }
            }

            return productCatalog;
        }

        private HttpClient GetApiClient()
        {
            var client = new HttpClient();
            var apiUrl = HttpContext.Request.Url.AbsoluteUri.Replace(this.HttpContext.Request.Url.PathAndQuery, "") + "/api/";
            client.BaseAddress = new Uri(apiUrl);

            return client;
        }

        private static string GetExportLink(GetProductCatalogsQuery query)
        {
            var exportPath = "/api/data_exchange";
            var exportQuery = GetSearchQueryString(query);

            if (exportQuery != null)
            {
                exportPath += exportQuery;
            }

            return exportPath;
        }

        private static string GetSearchQueryString(GetProductCatalogsQuery query)
        {
            string searchQueryString = null;

            if (!string.IsNullOrEmpty(query.Keyword))
            {
                searchQueryString = $"keyword={query.Keyword}";
            }

            if (query.From.HasValue)
            {
                if (searchQueryString != null)
                {
                    searchQueryString += "&";
                }

                searchQueryString += $"from={query.From.Value}";
            }

            if (query.To.HasValue)
            {
                if (searchQueryString != null)
                {
                    searchQueryString += "&";
                }

                searchQueryString += $"to={query.To.Value}";
            }

            if (query.Skip.HasValue)
            {
                if (searchQueryString != null)
                {
                    searchQueryString += "&";
                }

                searchQueryString += $"skip={query.Skip.Value}";
            }

            if (query.Limit.HasValue)
            {
                if (searchQueryString != null)
                {
                    searchQueryString += "&";
                }

                searchQueryString += $"limit={query.Limit.Value}";
            }

            if (!string.IsNullOrEmpty(query.Sort))
            {
                if (searchQueryString != null)
                {

CatalogsApp.Web/Views/ProductCatalog/Create.cshtml
@using CatalogsApp.Api.Models.Products
@model ProductCatalogModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Product Catalog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger", @type = "number", @min = "0" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastUpdated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastUpdated, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CatalogsApp.Web/Views/ProductCatalog/Delete.cshtml
@using CatalogsApp.Api.Models.Products
@model ProductCatalogModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product catalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CatalogsApp.Web/Views/ProductCatalog/Details.cshtml
@using CatalogsApp.Api.Models.Products
@model ProductCatalogModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product catalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CatalogsApp.Web/Views/ProductCatalog/Edit.cshtml
@using CatalogsApp.Api.Models.Products
@model ProductCatalogModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Product Catalog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger", @type = "number", @min = "0" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastUpdated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastUpdated, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CatalogsApp.Web/Views/ProductCatalog/Index.cshtml
@using PagedList.Mvc;
@using CatalogsApp.Api.Models.Products
@*@model IEnumerable<ProductCatalogModel>*@
@model PagedList.IPagedList<ProductCatalogModel>

@{
    ViewBag.Title = "Product catalogs";
}

<h2>Product catalogs</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "ProductCatalog", FormMethod.Get))
{
    <p>
        Find by code or name: @Html.TextBox("Keyword", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
@if (Model != null && ViewBag.ExportLink != null)
{
    <a href="@ViewBag.ExportLink">Export results</a>
}

@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Code", "Index", new { sortBy = "Code", currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Name", "Index", new { sortBy = "Name", currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Price", "Index", new { sortBy = "Price", currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Last Updated", "Index", new { sortBy = "LastUpdated", currentFilter = ViewBag.CurrentFilter })
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
    <br />
    <div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
}
<br />